### PR TITLE
Prepare 1.0.0

### PR DESCRIPTION
**Pull request by yaauie**
In preparation for a stable 1.0 release, this PR does two things:
 - bumps the version
 - makes a small clarification to the changelog

### CODE REVIEW

**Review by kares — APPROVED** [review]
:+1:

**Comment by kares** [comment]
also fine with leaving the **1.0.0** 'un-released' for now as there's more stuff we might need.
e.g. we'll need a ECS compatible event factory but that won't be available in older LS versions.
(not the cleanest way but since related its probably for the best to not have too many adapter gems)

**Comment by yaauie** [comment]
@kares a bunch of the prep-work originally included in this PR was merged in #3, and now we are left with the version bump and a _minor_ clarification in the changelog. I think we're ready to go 1.0.0. Can you re-review?

**Review by kares — APPROVED** [review]
:shipit:

**Pull request merged**
